version: '3.8'

services:
  jobsearcher_bot:
    build: .
    container_name: jobsearcher_bot
    restart: always
    volumes:
      - ./:/app
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '256M'
